name: Context Testing

on: pull_request

jobs:
  functions-test: 
    runs-on: ubuntu-latest
    steps:
      - name: Function Test
        continue-on-error: true #  even if it fails rest of the steps will be executed
        # timeout-minutes: 360
        run: |
          echo ${{ contains('hello', 'll')}}
          echo ${{ startsWith('hello', 'he')}}
          echo ${{ endsWith('hello', 'lo')}}
          echo ${{ format('Hello {0} {1} {2}', 'Word', '!', '!!')}}

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # don't need to put curly brackets in if statements
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: eccho '${{ toJSON(github) }}'
      - name: Dump job context
        if: failure() # this step will run even if in previous step is typo
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: always() # this step will always run
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'